import './postgres/security-and-read-side.test.js'
import './postgres/current-account-security.test.js'
import './postgres/current-account-inspection.test.js'
import './postgres/current-account-actions.test.js'
import './postgres/current-account-link.test.js'
import './postgres/current-account-reauth.test.js'
import './postgres/audit-pagination.test.js'
import './postgres/persistence-and-merge.test.js'
